Vagrant.configure("2") do |config|

  # Official Ubuntu 20.04 LTS (Focal Fossa)
  config.vm.box = "ubuntu/focal64"

  # config.vm.box_check_update = false

  # Create a private network, which allows host-only access to the machine using a
  # specific IP. This option is needed because DPDK takes over the NIC.
  config.vm.network "private_network", ip: "10.0.0.10"

  # VirtualBox-specific configuration
  config.vm.provider "virtualbox" do |vb|
    # Set machine name, memory and CPU limits
    vb.name = "ubuntu-20.04-dpdk"
    vb.memory = 4096
#    vb.cpus = 2
    vb.cpus = 4

    # Configure VirtualBox to enable passthrough of SSE 4.1 and SSE 4.2 instructions,
    # according to this: https://www.virtualbox.org/manual/ch09.html#sse412passthrough
    # This step is fundamental otherwise DPDK won't build. It is possible to verify in
    # the guest OS that these changes took effect by running `cat /proc/cpuinfo` and
    # checking that `sse4_1` and `sse4_2` are listed among the CPU flags.
    vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]

    # Allow promiscuous mode for host-only adapter
    vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
  end

  # Share file/folder with guest VM.
  config.vm.provision "file", source: "meson.build", destination: "meson.build"

  # Install DPDK
  config.vm.provision "shell", privileged: false, path: "install-dpdk.sh"

end
