Vagrant.configure("2") do |config|

  config.vm.box = "freebsd/FreeBSD-13.0-STABLE"

  # VirtualBox-specific configuration
  config.vm.provider "virtualbox" do |vb|
    # Set machine name
    vb.name = "freebsd-13.0-STABLE"
  end

  config.vm.provision "shell", path: "install.sh"
end
