Vagrant.configure("2") do |config|

  config.vm.box = "freebsd/FreeBSD-13.2-STABLE"

  # VirtualBox-specific configuration
  config.vm.provider "virtualbox" do |vb|
    # Set machine name, memory and CPU limits
    vb.name = "freebsd-13.2-STABLE"
    vb.memory = 8192
    vb.cpus = 8
  end
  # Requires the disksize plugin. Run in shell on host:
  # vagrant plugin install vagrant-disksize
  config.disksize.size = "25GB"

  config.vm.provision "shell", path: "install.sh"
end
